# frozen_string_literal: true

source "https://rubygems.org"

gem "dotenv"

# gem "omniauth"
# gem "omniauth-kakao", git: "https://github.com/shaynekang/omniauth-kakao.git"
gem "sb-omniauth-kakao", git: "https://github.com/ScriptonBasestar/sb-omniauth-kakao.git"

gem "sinatra"

gem "webrick"

gem "rackup"
# gem "rack"

gem "rubocop"

